name: Test

on:
    push:
    workflow_dispatch:

jobs:
    positive-control:
        name: Positive control
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/github-script@v2
              with:
                script: |
                    const path = require( 'path' );
                    await require( path.resolve( './simple.js' ) )( github, core, context );

    relative-require:
        name: Relative require()
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/github-script@v2
              with:
                script: |
                    await require( './simple.js' )( github, core, context );

    missing-dependency:
        name: Missing module dependency in script
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/github-script@v2
              with:
                script: |
                    const path = require( 'path' );
                    await require( path.resolve( './script-with-dependency.js' ) )( github, core, context );

    resolved-dependency:
        name: Install dependency before running script
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install --no-save node-fetch
            - uses: actions/github-script@v2
              with:
                script: |
                    const path = require( 'path' );
                    await require( path.resolve( './script-with-dependency.js' ) )( github, core, context );
